name: Yoklama Sistemi CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    
    - name: Python ${{ matrix.python-version }} kurulumu
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Bağımlılıkları yükle
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Testleri çalıştır
      run: |
        pytest --cov=app tests/
      env:
        DATABASE_URL: sqlite:///./test.db
        SECRET_KEY: test-secret-key
        JWT_SECRET_KEY: test-jwt-secret-key
        
    - name: Lint kontrolü
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=100 --statistics 